import Head from 'next/head'



export default function Home() {
  return (
   <>
      <Head>
        <title>create e-app</title>
        <meta name="description"  content="Generated by creae next app"/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <h1 className='bg-pink-700 font-bold py-4 px-4 hover:bg-pink-500 text-3xl' >E-sanabil </h1>
      </main>
    </>
  )
}
